---
title: "clean"
author: "Joshua Berry"
date: "2/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(GGally)
library(knitr)
library(gtsummary)
library(gt)
library(rstatix)
```

## R Markdown

```{r}
results <- read_csv("china_watch_combined.csv",
                    col_types = cols(Q17_1 = col_number(),
                                     Q18_1 = col_number(),
                                     Q19_1 = col_number(),
                                     Q22_1 = col_number(),
                                     Q40_1 = col_number(),
                                     Q41_1 = col_number(),
                                     Age = col_number()))

clean_results <- results %>%
  rename(race = Q92_1, ethnicity = Q92_2) %>%
   mutate(Q20 = case_when(Q20 == "Critical threat" ~ 2,
                                     Q20 == "Important but not critical threat" ~ 1,
                                     Q20 == "Not an important threat at all" ~ 0,
                                     TRUE ~ NA_real_)) %>%
     mutate(Q21_1 = case_when(Q21_1 == "Support" ~ 1,
                                     Q21_1 == "Oppose" ~ 0,
                                     TRUE ~ NA_real_)) %>%
   mutate(Q21_2 = case_when(Q21_2 == "Support" ~ 1,
                                     Q21_2 == "Oppose" ~ 0,
                                     TRUE ~ NA_real_)) %>%
   mutate(Q21_3 = case_when(Q21_3 == "Support" ~ 1,
                                     Q21_3 == "Oppose" ~ 0,
                                     TRUE ~ NA_real_)) %>%
   mutate(Q21_4 = case_when(Q21_4 == "Support" ~ 1,
                                     Q21_4 == "Oppose" ~ 0,
                                     TRUE ~ NA_real_)) %>%
     mutate(Q21_5 = case_when(Q21_5 == "Support" ~ 1,
                                     Q21_5 == "Oppose" ~ 0,
                                     TRUE ~ NA_real_)) %>%
     mutate(Q21_6 = case_when(Q21_6 == "Support" ~ 1,
                                     Q21_6 == "Oppose" ~ 0,
                                     TRUE ~ NA_real_)) %>%
 mutate(Q25 = case_when(Q25 == "0 hours" ~ 0,
                                     Q25 == "Less than 30 minutes" ~ 30,
                                     Q25 == "30-60 minutes" ~ 60,
                                     Q25 == "1-2 hours" ~ 120,
                                     Q25 == "More than 2 hours" ~ 150,
                                     TRUE ~ NA_real_)) %>%
   mutate(Q26 = case_when(Q26 == "No familiarity" ~ 1,
                                     Q26 == "Low familiarity with the news" ~ 2,
                                     Q26 == "Average familiarity with the news" ~ 3,
                                     Q26 == "High familiarity with the news" ~ 4,
                                     Q26 == "Complete familiarity with the news" ~ 5,
                                     TRUE ~ NA_real_)) %>%
   mutate(Q27 = case_when(Q27 == "Never" ~ 1,
                                     Q27 == "Sometimes" ~ 2,
                                     Q27 == "About half the time" ~ 3,
                                     Q27 == "Most of the time" ~ 4,
                                     Q27 == "Always" ~ 5,
                                     TRUE ~ NA_real_)) %>%
    mutate(Q28 = case_when(Q28 == "Totally disagree" ~ 1,
                                     Q28 == "Somewhat disagree" ~ 2,
                                     Q28 == "Neither agree nor disagree" ~ 3,
                                     Q28 == "Somewhat agree" ~ 4,
                                     Q28 == "Totally agree" ~ 5,
                                     TRUE ~ NA_real_)) %>%
      mutate(Q44 = case_when(Q44 == "Not at all" ~ 1,
                                     Q44 == "Not very well" ~ 2,
                                     Q44 == "Somewhat well" ~ 3,
                                     Q44 == "Very well" ~ 4,
                                     Q44 == "Extremely well" ~ 5,
                                     TRUE ~ NA_real_)) %>%
   rename(mediatrust = Q27, newsinterest = Q26, time_spent_news = Q25, newsconspiracy = Q44, newssource = Q43) %>%
           mutate(newssource = case_when(newssource == "Cable TV news broadcasts (For example: CNN, Fox News, or MSNBC)" ~ "Cable TV",
                                     newssource == "Blogs and other websites" ~ "Blogs and websites",
                                     newssource == "Facebook, Twitter and other social media" ~ "Social media",
                                     newssource == "Network TV news broadcasts (For example: ABC, CBS, or NBC)" ~ "Network TV",
                                     newssource == "Newspapers and news magazines" ~ "Newspapers and news magazines",
                                     newssource == "Radio" ~ "Radio",
                                     TRUE ~ NA_character_)) %>%
        mutate(Q34 = case_when(Q34 == "Not sure" ~ 0,
                                     Q34 == "More likely to support China" ~ -1,
                                     Q34 == "More likely to support the U.S." ~ 1,
                                     TRUE ~ NA_real_)) %>%
          mutate(Q42 = case_when(Q42 == "Not sure" ~ 0,
                                     Q42 == "More likely to support China" ~ -1,
                                     Q42 == "More likely to support the U.S." ~ 1,
                                     TRUE ~ NA_real_)) %>%
            mutate(Q35 = case_when(Q35 == "Yes" ~ -1,
                                     Q35 == "No" ~ 1,
                                     Q35 == "Not sure" ~ 0,
                                     TRUE ~ NA_real_)) %>%
              mutate(Education = case_when(Education == "Some high school" ~ 0,
                                     Education == "Less than high school degree" ~ 0,
                                     Education == "High school graduate" ~ 4,
                                     Education == "High school graduate (high school diploma or equivalent including GED)" ~ 4,
                                     Education == "B.A. or B.S." ~ 10,
                                     Education == "Bachelor's degree in college (4-year)" ~ 10,
                                     Education == "Associate's Degree" ~ 7,
                                     Education == "Associate degree in college (2-year)" ~ 7,
                                     Education == "Master's" ~ 12,
                                     Education == "Master's degree" ~ 12,
                                     Education == "Ph.D." ~ 17,
                                     Education == "M.D." ~ 17,
                                     Education == "Doctoral degree" ~ 17,
                                     TRUE ~ NA_real_)) %>%
                mutate(Gender = case_when(Gender == "Male" ~ "Male",
                                     Gender == "Female" ~ "Female",
                                     Gender == "Other" ~ "Other",
                                     TRUE ~ NA_character_)) %>%
                  mutate(Party = case_when(Party == "Republican" ~ "Republican",
                                     Party == "Democrat" ~ "Democrat",
                                     Party == "Other" ~ "Independent",
                                     Party == "Independent" ~ "Independent",
                                     TRUE ~ NA_character_)) %>%
                    mutate(Salary = case_when(Salary == "$90,000-$99,999" ~ 99999,
                                     Salary == "$35,000-$39,999" ~ 39999,
                                     Salary == "$22,000-$24,999" ~ 24999,
                                     Salary == "$75,000-$89,999" ~ 89999,
                                     Salary == "$45,000-$49,999" ~ 49999,
                                     Salary == "$60,000-$74,999" ~ 74999,
                                     Salary == "$135,000-$149,999" ~ 149999,
                                     Salary == "$50,000-$59,999" ~ 59999,
                                     Salary == "$100,000-$109,999" ~ 109999,
                                     Salary == "$15,000-$16,999" ~ 16999,
                                     Salary == "$60,000-$74,999" ~ 74999,
                                     Salary == "$30,000-$34,999" ~ 34999,
                                     Salary == "$17,000-$19,999" ~ 19999,
                                     Salary == "$120,000-$134,999" ~ 134999,
                                     Salary == "$110,000-$119,999" ~ 119999,
                                     Salary == "$150,000 and over" ~ 200000,
                                      Salary == "$40,000-$44,999" ~ 44999,
                                     Salary == "None or less than $2,999" ~ 2999,
                                     Salary == "$5,000 -$7,499" ~ 7499,
                                     Salary == "$100,000 to $149,999" ~ 149999,
                                     Salary == "$150,000 or more" ~ 200000,
                                     Salary == "$10,000 to $49,999" ~ 49999,
                                     Salary == "$50,000 to $74,999" ~ 74999,
                                     Salary == "Less than $10,000" ~ 10000,
                                     Salary == "$75,000 to $99,999" ~ 99999,
                                     TRUE ~ NA_real_)) %>%
                     mutate(race = case_when(race == "Asian" ~ "Asian",
                                     race == "Black" ~ "Black",
                                     race == "Hispanic" ~ "Hispanic",
                                     race == "Hispanic or Latino" ~ "Hispanic",
                                     race == "Other" ~ "Other",
                                     race == "White" ~ "White",
                                     race == "White,Asian" ~ "Other",
                                     race == "White,Black,Asian" ~ "Other",
                                     TRUE ~ NA_character_)) 

clean_results$condition <- factor(clean_results$condition, levels = c("peoplesdaily", "nytbase", "nytcw", "foxcw", "facebookcw"))

clean_results$race<- factor(clean_results$race, levels = c("Black", "Asian", "White", "Hispanic", "Other"))

clean_results$xicondition <- factor(clean_results$xicondition, levels = c("party", "children"))

mean(clean_results$Age, na.rm = TRUE)
```


```{r}
china.fav.lm <- lm(Q17_1 ~ Gender + Age + race + Education 
                + Party + condition, data = clean_results)

summary(china.fav.lm)

china.fav.tbl <-  tbl_regression(china.fav.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 1: Regression of China Watch Treatment Group Against Favorability Towards China", 
  subtitle = "Feeling Thermometer of 0 (Coldest) to 100 (Warmest)") %>%
    tab_source_note(md("Original DLABBS & MTURK Study, conducted 2021 Feb. 1-20, n = 417"))


china.fav.lm.news <- lm(Q17_1 ~ Gender + Age + race + Education 
                + Party + condition + mediatrust + newsinterest + time_spent_news
                + newsconspiracy + newssource, data = clean_results)

summary(china.fav.lm.news)

china.fav.news.tbl <-  tbl_regression(china.fav.lm.news, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 1a: Regression of China Watch Treatment Group and Media Interaction Against Favorability Towards China", 
  subtitle = "Feeling Thermometer of 0 (Coldest) to 100 (Warmest)") %>%
    tab_source_note(md("Original DLABBS & MTURK Study, conducted 2021 Feb. 1-20, n = 417"))

china.ppl.lm <- lm(Q22_1 ~ Gender + Age + race + Education 
                + Party + condition, data = clean_results)

summary(china.ppl.lm)

china.ppl.tbl <-  tbl_regression(china.ppl.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 2: Regression of China Watch Treatment Group Against Favorability Towards Chinese Citizens", 
  subtitle = "Feeling Thermometer of 0 (Coldest) to 100 (Warmest)") %>%
    tab_source_note(md("Original DLABBS & MTURK Study, conducted 2021 Feb. 1-20, n = 417"))

china.trust.lm <- lm(Q18_1 ~ Gender + Age + race + Education 
                + Party + condition, data = clean_results)

summary(china.trust.lm)

china.trust.tbl <-  tbl_regression(china.trust.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 3: Regression of China Watch Treatment Group Against Perceived Trust of China", 
  subtitle = "Scale of 1 (Untrustworthy) to 7 (Trustworthy)") %>%
    tab_source_note(md("Original DLABBS & MTURK Study, conducted 2021 Feb. 1-20,  n = 417"))



```

```{r}

china.influence.lm <- lm(Q19_1 ~ Gender + Age + race + Education 
                + Party + condition, data = clean_results)

summary(china.influence.lm)

china.influence.tbl <-  tbl_regression(china.influence.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 4: Regression of China Watch Treatment Group Against Perceived Influence of China", 
  subtitle = "Scale of 0 (Not at all influential) to 10 (Extremly influential)") %>%
    tab_source_note(md("Original DLABBS & MTURK Study, conducted 2021 Feb. 1-20, n = 417"))

china.threat.lm <- lm(Q20 ~ Gender + Age + race + Education 
                + Party + condition, data = clean_results)

summary(china.threat.lm)

china.threat.tbl <-  tbl_regression(china.threat.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 5: Regression of China Watch Treatment Group Against Belief that China is a 
             Threat to the United States", 
  subtitle = "Scale of 0 (Not an important threat at all) to 2 (Critical threat)") %>%
    tab_source_note(md("Original DLABBS & MTURK Study, conducted 2021 Feb. 1-20, n = 417"))

article.trust.lm <- lm(Q40_1 ~ Gender + Age + race + Education 
                + Party + condition, data = clean_results)

summary(article.trust.lm)

article.trust.tbl <-  tbl_regression(article.trust.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 6: Regression of China Watch Treatment Group Against 
             Trust in Accuracy of Treatment Article", 
  subtitle = "Scale of 1 (No trust) to 7 (Complete trust)") %>%
    tab_source_note(md("Original DLABBS & MTURK Study, conducted 2021 Feb. 1-20, n = 417"))


article.trust.news.lm <- lm(Q40_1 ~ Gender + Age + race + Education 
                + Party + condition + mediatrust + newsinterest + time_spent_news
                + newsconspiracy + newssource, data = clean_results)

summary(article.trust.news.lm)

article.trust.news.tbl <-  tbl_regression(article.trust.news.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 6a: Regression of China Watch Treatment Group and Media Interaction Against
             Trust in Accuracy of Treatment Article", 
  subtitle = "Scale of 1 (No trust) to 7 (Complete trust)") %>%
    tab_source_note(md("Original DLABBS & MTURK Study, conducted 2021 Feb. 1-20, n = 417"))

article.convincing.lm <- lm(Q41_1 ~ Gender + Age + race + Education 
                + Party + condition, data = clean_results)

summary(article.convincing.lm)

article.convincing.tbl <-  tbl_regression(article.convincing.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 7: Regression of China Watch Treatment Group Against 
             How Convinced Participants were by their Treatment Article", 
  subtitle = "Scale of 1 (Not convincing at all) to 7 (Very convincing)") %>%
    tab_source_note(md("Original DLABBS & MTURK Study, conducted 2021 Feb. 1-20, n = 417"))

article.convincing.news.lm <- lm(Q41_1 ~ Gender + Age + race + Education 
                + Party + condition + mediatrust + newsinterest + time_spent_news
                + newsconspiracy + newssource, data = clean_results)

summary(article.convincing.news.lm)

article.convincing.news.tbl <-  tbl_regression(article.convincing.news.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 7a: Regression of China Watch Treatment Group and Media Interaction Against 
             How Convinced Participants were of their Treatment Article", 
  subtitle = "Scale of 1 (Not convincing at all) to 7 (Very convincing)") %>%
    tab_source_note(md("Original DLABBS & MTURK Study, conducted 2021 Feb. 1-20, n = 417"))

china.trade.glm <- glm(Q21_1 ~ Gender + Age + race + Education 
                + Party + condition, data = clean_results)

summary(china.trade.glm)

china.trade.tbl <-  tbl_regression(china.trade.glm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 8: Logistic Regression of China Watch Treatment Group Against 
             Policy Preference regarding Trade Tariffs", 
  subtitle = "Scale of 0 (Oppose) to 1 (Support)") %>%
    tab_source_note(md("Original DLABBS & MTURK Study, conducted 2021 Feb. 1-20, n = 417"))

china.hrights.glm <- glm(Q21_3 ~ Gender + Age + race + Education 
                + Party + condition, data = clean_results)

summary(china.hrights.glm)

```

```{r}
china.research.glm <- glm(Q21_2 ~ Gender + Age + race + Education 
                + Party + condition, data = clean_results)

summary(china.research.glm)

china.research.tbl <-  tbl_regression(china.research.glm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 9: Logistic Regression of China Watch Treatment Group Against 
  Policy Preference regarding Restricting US-China Scientific Exchange", 
  subtitle = "Scale of 0 (Oppose) to 1 (Support)") %>%
    tab_source_note(md("Original DLABBS & MTURK Study, conducted 2021 Feb. 1-20, n = 417"))


china.research.news.glm <- glm(Q21_2 ~ Gender + Age + race + Education 
                + Party + condition + mediatrust + newsinterest + time_spent_news
                + newsconspiracy + newssource, data = clean_results)

summary(china.research.news.glm)

china.research.news.tbl <-  tbl_regression(china.research.news.glm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 9a: Regression of China Watch Treatment Group and Media Interaction Against 
             Policy Preference regarding Restricting US-China Scientific Exchange", 
  subtitle = "Scale of 0 (Oppose) to 1 (Support)") %>%
    tab_source_note(md("Original DLABBS & MTURK Study, conducted 2021 Feb. 1-20, n = 417"))

china.students.glm <- glm(Q21_4 ~ Gender + Age + race + Education 
                + Party + condition, data = clean_results)

summary(china.students.glm)

china.dvlpment.glm <- glm(Q21_5 ~ Gender + Age + race + Education 
                + Party + condition, data = clean_results)

summary(china.dvlpment.glm)

china.military.glm <- glm(Q21_6 ~ Gender + Age + race + Education 
                + Party + condition, data = clean_results)

summary(china.military.glm)


```


```{r}
chineseamericans.economic.lm <- lm(Q34 ~ Gender + Age + race + Education 
                + Party + xicondition, data = clean_results)

summary(chineseamericans.economic.lm)

chineseamericans.economic.tbl <-  tbl_regression(chineseamericans.economic.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 10: Regression of Xi Quote Treatment Against 
             Perceived Economic Threat of Chinese American Fifth Column", 
  subtitle = "Scale of -1 (Chinese Americans are more likely to support China) 
  to 1 (Chinese Americans are more likely to support the U.S.)") %>%
    tab_source_note(md("Original DLABBS & MTURK Study, conducted 2021 Feb. 1-20, n = 417"))

chineseamericans.military.lm <- lm(Q42 ~ Gender + Age + race + Education 
                + Party + xicondition, data = clean_results)

summary(chineseamericans.military.lm)

chineseamericans.military.tbl <-  tbl_regression(chineseamericans.military.lm, intercept = TRUE,
                 estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
  as_gt() %>%
  tab_header(title = "Tbl. 11: Regression of Xi Quote Treatment Against 
             Perceived Military Threat of Chinese American Fifth Column", 
  subtitle = "Scale of -1 (Chinese Americans are more likely to support China) 
  to 1 (Chinese Americans are more likely to support the U.S.)") %>%
    tab_source_note(md("Original DLABBS & MTURK Study, conducted 2021 Feb. 1-20, n = 417"))


chineseamericans.military.news.lm <- lm(Q42 ~ Gender + Age + race + Education 
                + Party + xicondition + mediatrust + newsinterest + time_spent_news
                + newsconspiracy + newssource, data = clean_results)

summary(chineseamericans.military.news.lm)

chineseamericans.economic.news.lm <- lm(Q34 ~ Gender + Age + race + Education 
                + Party + xicondition + mediatrust + newsinterest + time_spent_news
                + newsconspiracy + newssource, data = clean_results)

summary(chineseamericans.economic.news.lm)

chineseamericans.securityrisk.lm <- lm(Q35 ~ Gender + Age + race + Education 
                + Party + xicondition, data = clean_results)

summary(chineseamericans.securityrisk.lm)

```

```{r}
source_id_graph <- clean_results %>%
  filter(Q39 %in% c("China Daily", "Fox News", "Not sure", "The New York Times", "People.cn (China's People's Daily)", "Facebook News")) %>%
ggplot(aes(x = Q39, fill = condition)) +
  geom_bar(na.rm = TRUE) +
  scale_fill_discrete(name = "Treatment", labels = c("People's Daily", "NYT Base",
                         "NYT CW", "Fox CW", "Facebook CW")) +
  scale_x_discrete(labels=c("China Daily", "Fox News",
                         "Not sure", "People's Daily", "New York Times", "Facebook News")) +
  labs(title = "Participant Identification of Authoring Media Source",
       subtitle = "Legend indicates the treatment participants actually received; CW = China Watch treatment",
       x = "Participants' Source ID",
       y = "Count",
       source = "Original DLABBS & MTurk study, conducted 2021 Feb. 1-20, n = 417") +
  theme_bw()

mean_china_fav <-
  clean_results %>%
  group_by(condition) %>%
  summarize(mean_china_fav = mean(Q17_1, na.rm = TRUE),
            sd = sd(Q17_1, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower.ci = mean_china_fav - qt(1 - (0.05 / 2), n - 1) * se,
         upper.ci = mean_china_fav + qt(1 - (0.05 / 2), n - 1) * se)


china_fav_graph <-
  mean_china_fav %>%
  drop_na(condition) %>%
ggplot(aes(x = condition, y = mean_china_fav, fill = condition)) +
  geom_col(position=position_dodge()) +
  geom_errorbar(mapping = aes(x = condition, ymin = lower.ci, ymax = upper.ci),
                width = .2) + 
  ylim(0, 100) +
  scale_fill_discrete(name = "Condition", labels = c("People's Daily", "NYT Base",
                         "NYT CW", "Fox CW", "Facebook CW")) +
  scale_x_discrete(labels=c("People's Daily", "NYT Base",
                         "NYT CW", "Fox CW", "Facebook CW")) +
  labs(title = "Fig. 1: The Effect of Media Treatment on Favorability Towards China",
       subtitle = "Feeling Thermometer of 0 (Coldest) to 100 (Warmest)",
       x = "Treatment Group",
       y = "Mean Favorability towards China",
       source = "Original DLABBS and MTurk study, conducted 2021 Feb. 1-20, n = 417") +
  theme_bw() 

mean_china_ppl_fav <-
  clean_results %>%
  group_by(condition) %>%
  summarize(mean_china_ppl_fav = mean(Q22_1, na.rm = TRUE),
            sd = sd(Q22_1, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower.ci = mean_china_ppl_fav - qt(1 - (0.05 / 2), n - 1) * se,
         upper.ci = mean_china_ppl_fav + qt(1 - (0.05 / 2), n - 1) * se)

china_fav_ppl_graph <-
  mean_china_ppl_fav %>%
    drop_na(condition) %>%
ggplot(aes(x = condition, y = mean_china_ppl_fav, fill = condition)) +
  geom_col(position=position_dodge()) +
  geom_errorbar(mapping = aes(x = condition, ymin = lower.ci, ymax = upper.ci),
                width = .2) + 
  ylim(0, 100) +
  scale_fill_discrete(name = "Condition", labels = c("People's Daily", "NYT Base",
                         "NYT CW", "Fox CW", "Facebook CW")) +
  scale_x_discrete(labels=c("People's Daily", "NYT Base",
                         "NYT CW", "Fox CW", "Facebook CW")) +
  labs(title = "Fig. 2: The Effect of Media Treatment on Favorability Towards Chinese People",
       subtitle = "Feeling Thermometer of 0 (Coldest) to 100 (Warmest)",
       x = "Treatment Group",
       y = "Mean Favorability towards Chinese People",
       source = "Original DLABBS and MTurk study, conducted 2021 Feb. 1-20, n = 417") +
  theme_bw()
```

```{r}
mean_china_trust_fav <-
  clean_results %>%
  group_by(condition) %>%
  summarize(mean_china_trust_fav = mean(Q18_1, na.rm = TRUE),
            sd = sd(Q18_1, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower.ci = mean_china_trust_fav - qt(1 - (0.05 / 2), n - 1) * se,
         upper.ci = mean_china_trust_fav + qt(1 - (0.05 / 2), n - 1) * se)

china_trust_graph <-
  mean_china_trust_fav %>%
    drop_na(condition) %>%
ggplot(aes(x = condition, y = mean_china_trust_fav, fill = condition)) +
  geom_col(position=position_dodge()) +
  geom_errorbar(mapping = aes(x = condition, ymin = lower.ci, ymax = upper.ci),
                width = .2) + 
  ylim(0, 7) +
  scale_fill_discrete(name = "Condition", labels = c("People's Daily", "NYT Base",
                         "NYT CW", "Fox CW", "Facebook CW")) +
  scale_x_discrete(labels=c("People's Daily", "NYT Base",
                         "NYT CW", "Fox CW", "Facebook CW")) +
  labs(title = "Fig. 3: The Effect of Media Treatment on Perceived Trust of China",
       subtitle = "Scale of 1 (Untrustworthy) to 7 (Trustworthy)",
       x = "Treatment Group",
       y = "Mean Trust",
       source = "Original DLABBS and MTurk study, conducted 2021 Feb. 1-20, n = 417") +
  theme_bw()

mean_china_influence <-
  clean_results %>%
  group_by(condition) %>%
  summarize(mean_china_influence = mean(Q19_1, na.rm = TRUE),
            sd = sd(Q19_1, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower.ci = mean_china_influence - qt(1 - (0.05 / 2), n - 1) * se,
         upper.ci = mean_china_influence + qt(1 - (0.05 / 2), n - 1) * se)

china_influence_graph <-
  mean_china_influence %>%
    drop_na(condition) %>%
ggplot(aes(x = condition, y = mean_china_influence, fill = condition)) +
  geom_col(position=position_dodge()) +
  geom_errorbar(mapping = aes(x = condition, ymin = lower.ci, ymax = upper.ci),
                width = .2) + 
  ylim(0, 10) +
  scale_fill_discrete(name = "Condition", labels = c("People's Daily", "NYT Base",
                         "NYT CW", "Fox CW", "Facebook CW")) +
  scale_x_discrete(labels=c("People's Daily", "NYT Base",
                         "NYT CW", "Fox CW", "Facebook CW")) +
  labs(title = "Fig. 4: The Effect of Media Treatment on Perceived Influence of China",
       subtitle = "Scale of 0 (Not at all influential) to 10 (Extremly influential)",
       x = "Treatment Group",
       y = "Mean Influence Rating",
       source = "Original DLABBS and MTurk study, conducted 2021 Feb. 1-20, n = 417") +
  theme_bw()
```

```{r}
mean_china_threat <-
  clean_results %>%
  group_by(condition) %>%
  summarize(mean_china_threat = mean(Q20, na.rm = TRUE),
            sd = sd(Q20, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower.ci = mean_china_threat - qt(1 - (0.05 / 2), n - 1) * se,
         upper.ci = mean_china_threat + qt(1 - (0.05 / 2), n - 1) * se)

china_threat_graph <-
  mean_china_threat %>%
    drop_na(condition) %>%
ggplot(aes(x = condition, y = mean_china_threat, fill = condition)) +
  geom_col(position=position_dodge()) +
  geom_errorbar(mapping = aes(x = condition, ymin = lower.ci, ymax = upper.ci),
                width = .2) + 
  ylim(0, 2) +
  scale_fill_discrete(name = "Condition", labels = c("People's Daily", "NYT Base",
                         "NYT CW", "Fox CW", "Facebook CW")) +
  scale_x_discrete(labels=c("People's Daily", "NYT Base",
                         "NYT CW", "Fox CW", "Facebook CW")) +
  labs(title = "Fig. 5: The Effect of Media Treatment on Belief that China is a 
             Threat to the United States",
       subtitle = "Scale of 0 (Not an important threat at all) to 2 (Critical threat)",
       x = "Treatment Group",
       y = "Mean Threat Rating",
       source = "Original DLABBS and MTurk study, conducted 2021 Feb. 1-20, n = 417") +
  theme_bw()

mean_article_trust <-
  clean_results %>%
  group_by(condition) %>%
  summarize(mean_article_trust = mean(Q40_1, na.rm = TRUE),
            sd = sd(Q40_1, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower.ci = mean_article_trust - qt(1 - (0.05 / 2), n - 1) * se,
         upper.ci = mean_article_trust + qt(1 - (0.05 / 2), n - 1) * se)

article_trust_graph <-
  mean_article_trust %>%
    drop_na(condition) %>%
ggplot(aes(x = condition, y = mean_article_trust, fill = condition)) +
  geom_col(position=position_dodge()) +
  geom_errorbar(mapping = aes(x = condition, ymin = lower.ci, ymax = upper.ci),
                width = .2) + 
  ylim(0, 7) +
  scale_fill_discrete(name = "Condition", labels = c("People's Daily", "NYT Base",
                         "NYT CW", "Fox CW", "Facebook CW")) +
  scale_x_discrete(labels=c("People's Daily", "NYT Base",
                         "NYT CW", "Fox CW", "Facebook CW")) +
  labs(title = "Fig. 6: The Effect of Media Treatment on Trust in Accuracy of Treatment Article",
       subtitle = "Scale of 1 (No trust) to 7 (Complete trust)",
       x = "Treatment Group",
       y = "Mean Trust",
       source = "Original DLABBS and MTurk study, conducted 2021 Feb. 1-20, n = 417") +
  theme_bw()

mean_article_convince <-
  clean_results %>%
  group_by(condition) %>%
  summarize(mean_article_convince = mean(Q41_1, na.rm = TRUE),
            sd = sd(Q41_1, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower.ci = mean_article_convince - qt(1 - (0.05 / 2), n - 1) * se,
         upper.ci = mean_article_convince + qt(1 - (0.05 / 2), n - 1) * se)

article_convince_graph <-
  mean_article_convince %>%
    drop_na(condition) %>%
ggplot(aes(x = condition, y = mean_article_convince, fill = condition)) +
  geom_col(position=position_dodge()) +
  geom_errorbar(mapping = aes(x = condition, ymin = lower.ci, ymax = upper.ci),
                width = .2) + 
  ylim(0, 7) +
  scale_fill_discrete(name = "Condition", labels = c("People's Daily", "NYT Base",
                         "NYT CW", "Fox CW", "Facebook CW")) +
  scale_x_discrete(labels=c("People's Daily", "NYT Base",
                         "NYT CW", "Fox CW", "Facebook CW")) +
  labs(title = "Fig. 6: The Effect of Media Treatment on 
       How Convinced Participants were by their Treatment Article",
       subtitle = "Scale of 1 (Not convincing at all) to 7 (Very convincing)",
       x = "Treatment Group",
       y = "Mean Convincement",
       source = "Original DLABBS and MTurk study, conducted 2021 Feb. 1-20, n = 417") +
  theme_bw()
```

```{r}
mean_chineseamerican_military <-
  clean_results %>%
  group_by(condition) %>%
  summarize(mean_chineseamerican_military = mean(Q42, na.rm = TRUE),
            sd = sd(Q42, na.rm = TRUE),
            n = n()) %>%
  mutate(se = sd / sqrt(n),
         lower.ci = mean_chineseamerican_military - qt(1 - (0.05 / 2), n - 1) * se,
         upper.ci = mean_chineseamerican_military + qt(1 - (0.05 / 2), n - 1) * se)

chineseamerican_military_graph <-
  mean_chineseamerican_military %>%
    drop_na(condition) %>%
ggplot(aes(x = condition, y = mean_chineseamerican_military, fill = condition)) +
  geom_col(position=position_dodge()) +
  geom_errorbar(mapping = aes(x = condition, ymin = lower.ci, ymax = upper.ci),
                width = .2) + 
  ylim(-1, 1) +
  scale_fill_discrete(name = "Condition", labels = c("People's Daily", "NYT Base",
                         "NYT CW", "Fox CW", "Facebook CW")) +
  scale_x_discrete(labels=c("People's Daily", "NYT Base",
                         "NYT CW", "Fox CW", "Facebook CW")) +
  labs(title = "Fig. 7: The Effect of Media Treatment on 
       Perceived Military Threat of Chinese American Fifth Column",
       subtitle = "Scale of -1 (Chinese Americans are more likely to support China) 
  to 1 (Chinese Americans are more likely to support the U.S.)",
       x = "Treatment Group",
       y = "Mean Rating",
       source = "Original DLABBS and MTurk study, conducted 2021 Feb. 1-20, n = 417") +
  theme_bw()
```

